### ISSUE TITLE
spacy_component

### ISSUE THREAD

**Issue by gossebouma** [Babelscape/rebel#15]
Hi, 
for me spacy integration only worked after the following fix:

$ diff spacy_component.py fix_spacy_component.py 
71c71
<           extracted_text = self.triplet_extractor.tokenizer.batch_decode(output_ids[0])
---
>           extracted_text = self.triplet_extractor.tokenizer.batch_decode(output_ids)

(the decode function assumes a list of lists, not a list of ids, it wont raise an error but only first token is processed in the buggy version)

**Comment by LittlePea13** [comment]
I believe this has to do with the transformers library version. Could you share yours?

**Comment by gossebouma** [comment]
4.15.0

**Comment by LittlePea13** [comment]
Hi, it seems that the behavior of `batch_decode` changed from 4.17.0. So for now I can suggest to update the version to use the Spacy component.

I am looking to update the requirements version, but I want to check whether it requires to update other parts of the code.

Please let me know if updating the transformers version fix the issue for you.
