### ISSUE TITLE
spaCy not working

### ISSUE THREAD

**Issue by CoolOppo** [Babelscape/rebel#24]
I get this error when running the code in the readme:

```
TypeError: Can't convert {'output_ids': [[[0, 50267, 2974, 5269, 14555, 1437, 50266, 4612, 1437, 50265, 2034, 11, 5, 6833, 15752, 10014, 1437, 50266, 2809, 1437, 50265, 247, 1437, 50267, 4612, 1437, 50266, 2974, 5269, 14555, 1437, 50265, 6308, 6833, 15752, 10014, 1437, 50266, 2809, 1437, 50265, 247, 2]]]} to Sequence
```

**Comment by CoolOppo** [comment]
Commit #9852dfa3cadaed19f644fab749d3488727f88cb8 works fine

**Comment by LittlePea13** [comment]
Could you share your transformers version?

**Comment by LittlePea13** [comment]
Just in case, here is a colab notebook with the spacy component working with the latest transformers and spacy libraries. 

[REBEL spacy](https://colab.research.google.com/drive/1tizTmOVA3fyBzOKcvpLteAeMZ4Rwz8qG?usp=sharing)

I am closing the issue, feel free to reopen if still facing issues.
