### ISSUE TITLE
relation_counts.tsv has 230 relations not 220

### ISSUE THREAD

**Issue by bablf** [Babelscape/rebel#31]
Hi, 
great paper! 

In your paper you state that you train on 220 relations but relation_counts.tsv has 230 relations. Is that a typo in the paper or is the relations file outdated? 

> To pre-train our model, we use a sentence-
level version of it, where only relations between
entities present in each sentence are kept. We keep
the 220 most frequent relations in the train split.
We fine-tune REBEL (using BART-large as the
base model) on the silver dataset for 6 epochs. We
refer to the resulting model as REBELpre−training.
While REBELpre−training is in and of itself capa-
ble of extracting relations subsuming about 220
types, we show that it also functions as a base step
for downstream RE and RC tasks, which are fine-
tuned on top of it.

**Comment by LittlePea13** [comment]
Yes, you are right, it is a typo. I believe the confusion comes from the fact that it was evaluated on 220 relations (since 10 were missing from the set used for evaluation). Thanks for pointing it out.
