### ISSUE TITLE
Fine-Tuning with custom dataset

### ISSUE THREAD

**Issue by aliceinland** [Babelscape/rebel#36]
Hi! I was trying to fine-tune the model with my custom dataset. 
I did not find anything and could not do this operation by modifying the config hydra file inside the directory. Is there a way to perform this operation?

**Comment by LittlePea13** [comment]
Unfortunately the library is not as modular as I would wish to make it codeless to finetune on your own data, perhaps I will get into it in the future. 

As it is now, there are a few things you need to change other than the config hydra files. Make sure that you deal with your entity types with special tokens and the relation types when evaluating. I suggest you look at for instance at what changes when fine-tuning on CONLL04 at pl_modules.py and train.py (by searching to references to "conll04_typed"), and adapt it in a similar fashion to your use case.

Best of luck.
