### ISSUE TITLE
Whats the token for token_id 50265?

### ISSUE THREAD

**Issue by ambiSk** [Babelscape/rebel#38]
In the `BasePLModule`, in line [217](https://github.com/Babelscape/rebel/blob/main/src/pl_modules.py#L217) and [231](https://github.com/Babelscape/rebel/blob/main/src/pl_modules.py#L231), a variable is storing a boolean matrix with condition that `labels==50265` and `generated_tokens==50265`. I would like to know in your repo whats the token for token id `50265`.

**Comment by LittlePea13** [comment]
Truth is those methods are no longer used, they served to somewhat accelerate generation at some point. Now `generate_triplets` is used. Nevertheless to satisfy your curiosity, it was the `<triplet>` token.

**Comment by ambiSk** [comment]
Actually I am trying to train it with some additional data, as its precision is lower than 50% on news article.
