### ISSUE TITLE
Architecture of REBEL model

### ISSUE THREAD

**Issue by Vishwanathts01** [Babelscape/rebel#43]
Hello,
Thank you so much for your work. Could you please upload the model architecture? or is it same as transformer architecture?

**Comment by LittlePea13** [comment]
Hi there,
REBEL is based on Bart-large. It's weights can be found in [Huggingface](https://huggingface.co/Babelscape/rebel-large), and easily loaded by:
```
from transformers import pipeline
triplet_extractor = pipeline('text2text-generation', model='Babelscape/rebel-large', tokenizer='Babelscape/rebel-large')
```
if you just need it for inference.
