### ISSUE TITLE
ValueError: Invalid file path or buffer object type: <class 'datasets.data_files.DataFilesList'>

### ISSUE THREAD

**Issue by LawsonAbs** [Babelscape/rebel#44]
When I run the "python train.py" in command line, follwing error is thrown:
![image](https://user-images.githubusercontent.com/35190068/194822180-40f2e5fe-fa09-4e1e-b2cd-d2088078de07.png)
Can you help me ? Thank you very much!

**Comment by LittlePea13** [comment]
Check https://github.com/Babelscape/rebel/issues/32

Hope that helps,
Pere-Lluis.
