### ISSUE TITLE
What is the concrete data format of examples that conveyed to preprocess_function?

### ISSUE THREAD

**Issue by LawsonAbs** [Babelscape/rebel#45]
I'm a little confused about the data format that conveyed to preprocess_function? 
![image](https://user-images.githubusercontent.com/35190068/194891079-c5549151-37fa-4c3f-94f0-d110529bdb22.png)

I am very grateful for your help.

**Comment by LawsonAbs** [comment]
I think I have found the answer. Towards different dataset, there are different way to generate examples. The file is located in datasets, such as the _generate_examples() function in conll04_typed.json. Is that so?

**Comment by LittlePea13** [comment]
Hi, sorry for the late reply, it has been a busy week. Indeed we use the datasets library to load each dataset file in the linearized triplets version REBEL expects for training. preprocess_function only takes care of the tokenization part.
