### ISSUE TITLE
Do you have the results data of wikiextractor and crocodile?

### ISSUE THREAD

**Issue by DantaAlighieri** [Babelscape/rebel#5]
There are many problems that caused I can't get the result of WikiExtractor and crocodile. Could you please upload your result data to google drive? 
I am really want to run your models. I spent many days, however, I can't succeed.

**Comment by DantaAlighieri** [comment]
This Step' results, please.

CROCODILE: automatiC RelatiOn extraCtiOn Dataset wIth nLi filtEring.
REBEL dataset can be recreated using our RE dataset creator CROCODILE

**Comment by LittlePea13** [comment]
Hi, you can find the dataset used for the paper at [HF](https://huggingface.co/datasets/Babelscape/rebel-dataset).

Good luck with your work.
