### ISSUE TITLE
Can this method serves to Chinese dataset?

### ISSUE THREAD

**Issue by AndDoIt** [Babelscape/rebel#6]
Since BART-large model pre-trained on the English language, and the datasets in the paper are all English, I wondered whether this method serves to Chinese dataset while Chinese relation extraction datasets are also scarce and often small? If yes, how to apply the specific transform?

**Comment by LittlePea13** [comment]
Hello there.

The silver dataset creation could be expanded to Chinese. I recommend you check the [crocodile](https://github.com/Babelscape/crocodile) repo where you can create a dataset from a Wikipedia dump.

Best,
Pere-Lluis.
