### ISSUE TITLE
Explainability of REBEL

### ISSUE THREAD

**Issue by sky-2002** [Babelscape/rebel#64]
Hi @m0baxter @LittlePea13 @DavidFromPandora @tomasonjo , thanks for this amazing repo. 
I am currently using REBEL to do relation extraction. I wanted to know if there is any way to evaluate these relations, or having some explainability mechanism for this model, so that we know what features it looks into text to generate the relations. 
I wanted to know this because in my use case, I am getting some correct relations with low confidence score, so I want to see what words or features in the text make the model generate them. Any suggestions will be helpful.

**Comment by LittlePea13** [comment]
Hi @sky-2002, sorry for the late reply, I was busy last week. 

So REBEL as it is isn't able to provide the information you look for, however, there are explainability methods that may help. It seems you want to know what part of the input is "responsible" for certain predictions. I would encourage you to look into the [Inseq](https://github.com/inseq-team/inseq) library which provides extensive tools for interpretability methods for seq2seq models. I believe also looking at the cross-attention may provide some useful information.

As I said, this is not covered by the current repo, but if you find anything interesting using these tools don't hesitate to report them here or contribute with a pull request.
