### ISSUE TITLE
Extraction of non-existant relation

### ISSUE THREAD

**Issue by sky-2002** [Babelscape/rebel#67]
@LittlePea13 @tomasonjo @m0baxter @DavidFromPandora  Hi. Firstly, thanks a lot for this amazing REBEL model. I have been using it quite a lot. While experimenting with it, I came across some instances where the model is extracting non-existant relations(probably due to the way in which entities appear in the sentnece). 
For example, consider the below image:
![image](https://github.com/Babelscape/rebel/assets/84656834/d8a5b84e-6a47-4caf-9714-f25e7434f458)
Consider the sentence `Bruce Springsteen's 
speaking out against the Berlin Wall in the middle of East Berlin added to the euphoria`, in this sentence, the event mentioned is `Bruce Springsteen speaking in the middle of East Berlin`. 
But the model considered `Berlin Wall` and `East Berlin` as entities, probably due to `Berlin Wall in the middle of East Berlin` part.
- Can this behaviour be avoided or corrected by some means? 
- Can you point me to more recent works on relation extraction, or even something that you people at babelscape are working on?

**Comment by LittlePea13** [comment]
Hi there, yes, it seems the model is extracting the wrong relation there. Unfortunately, this will happen, probably exacerbated by the nature of the silver data used for training, where it sees too many location-based relations, making it a bit biased towards predicting them (If you check https://www.wikidata.org/wiki/Q5086, it says the Berlin wall was located in East Berlin as well).

In the sentence you mention there is added ambiguity, as "in the middle of East Berlin" could refer to either Bruce or the Berlin Wall.

So this concrete example would be hard to tackle. Check the answers I gave in this other issue https://github.com/Babelscape/rebel/issues/66 which is somewhat related.

Regarding more recent work, you can check [USM](https://arxiv.org/abs/2301.03282) which had very promising results. Unfortunately, it is not openly available. Us in Babelscape and SapienzaNLP are always working towards new research, including Relation Extraction, so stay tuned. We recently released some work on a [multilingual RE dataset and a multilingual version of REBEL, mREBEL](https://aclanthology.org/2023.acl-long.237/)
