### ISSUE TITLE
Issue while running the default_model on training with conl dataset

### ISSUE THREAD

**Issue by mayanku** [Babelscape/rebel#68]
How to get the conll files. Are these files auto creating. How to customise for my dataset.

train_file: '/home/martinez/rebel/data/conll04/conll04_train.json'
validation_file: '/home/martinez/rebel/data/conll04/conll04_dev.json'
test_file: '/home/martinez/rebel/data/conll04/conll04_test.json'

there are no json files in these locations hence giving error

**Comment by LittlePea13** [comment]
Read the README carefully, you will find where to download those files there.

**Comment by mayanku** [comment]
What should be the path and the downloaded files will be json? I am not getting those file.
