### ISSUE TITLE
version incompatible

### ISSUE THREAD

**Issue by S1Koy** [Babelscape/rebel#72]
transformers 4.19.2 need huggingface-hub >= 0.1.0, but datasets-1.3.0 need huggingfac-hub-0.0.2, Have solution?

**Comment by 4theKnowledge** [comment]
I'm successfully using REBEL with the following:
- `transformers==4.34.0`
- `tokenizers==0.14.1`
- `datasets==2.14.5`
- `huggingface-hub==0.18.0`
- `torch==2.1.0+cu121`
- `pytorch-lightning==2.1.0`

You need to update the associated methods in `pl_modules.py` if you update the pytorch-lightning dependency as per https://github.com/Lightning-AI/lightning/pull/16520.

**Comment by LittlePea13** [comment]
Sorry about that, thanks @4theKnowledge for the Knowledge about versions, I will update the reqs
